# Generated by Django 3.2.5 on 2021-11-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=30)),
                ('especialidade', models.CharField(max_length=30)),
                ('mostrar', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('nome_paciente', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
