# Generated by Django 3.2.5 on 2021-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='nome_medico',
            field=models.CharField(max_length=50),
        ),
    ]
