# Generated by Django 3.2.5 on 2021-11-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_nome_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='nome_paciente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
